platform :ios ,'8.0'
target 'BicycleApp' do
pod 'Masonry'
pod 'SDWebImage'
pod 'MJRefresh'
pod 'IQKeyboardManager'
pod 'MBProgressHUD'
pod 'WechatOpenSDK'
pod 'YYModel'
pod 'YTKKeyValueStore'
pod 'AMap3DMap'
pod 'AMapSearch'
pod 'AMapLocation'
pod 'XHLaunchAd'
end 
